### ISSUE TITLE
Episodes are added before Aired time

### ISSUE THREAD

**Issue by jorgefpcardoso** [a4k-openproject/plugin.video.openmeta#28] opened 2019-07-11 10:27 UTC
Hi,

Normaly the addon adds, to the kodi library, the tv shows episodes on the day they are released, but we can only get torrents to see them the day after.
There is any way to only add the episodes to the kodi library the day after they have been released?

thanks in advance,

**Comment by SOOTTV** [comment] 2019-07-11 16:02
This isn't true. I'm able to watch shows an hour after they're released. Please don't make this a part of the base code. Or if you do, make it a toggle in the settings

**Comment by jorgefpcardoso** [comment] 2019-07-11 16:11
Maybe I don't explain my problem well enough.

What I mean is, for example, the episode 7x08 of Elementary, only airs day 12 if July, in my time zone, and it has already been added to my library.

Is there any way to fix it?

Thanks

**Comment by SOOTTV** [comment] 2019-07-11 17:36
I get what you're saying. But in the US episodes air and are available on Wednesday so the most recent would be July 10, 2019. If the air date is switched for you then people in the states wouldn't get the episode until 2 days later.. That's why I asked for a toggle or setting for people in different time-zones/ countries. In addition, if the episode is available in the US on Wednesday July, 10 then it's available for you on the same day, regardless of where you are. If you are looking for dubbed versions or subtitles you may have to wait longer but, in general, the episode is available an hour after it airs everywhere

**Comment by drinfernoo** [comment] 2019-07-11 17:47
There are add-ons that can handle this, only showing episodes as "aired" based in th time zone of the user's system. We can see about implementing a similar system.

**Comment by jorgefpcardoso** [comment] 2019-07-12 07:49
Can you you recomendo and addon that can do what you are describing?

Thanks

**Comment by drinfernoo** [comment] 2019-07-12 17:26
@jorgecardoso220 I don't know of any that do this that *also* handle library integration, so that may not work for you.

**Comment by jorgefpcardoso** [comment] 2019-07-12 18:20
this happens in library integration. any ideia how to solve this?

**Comment by drinfernoo** [comment] 2019-07-12 19:08
@jorgecardoso220 At this point there isn't a good solution. I'd recommend paying closer attention to what days your shows air.

**Comment by jorgefpcardoso** [comment] 2019-07-13 08:50
O had this same problem in the elementum addon and the programer was able to solve the problem. This was what he said 

“
I have found the cause of this issue. It was because tmdb date, like "2018-14-02" was translated to "2018-14-02 00:00:00" was compared to current time, which, for example is "2018-14-02 00:00:01" and so it's always after current date.”

Hope that developers can solve this issue

**Comment by drinfernoo** [comment] 2019-07-15 16:19
Duplicate of #9.

**Comment by Sikriffs** [comment] 2020-04-07 13:33
Has a solution been found.  It seems issue's #28 and #9 link to each other but neither have a solution.

The main issue (for me) with having the episodes loaded at 12:00am on the airdate is that it's too early for there to be episode thumbnails to scrape.  This problem persists on all new episodes and they need to be refreshed to load the thumbnail.  

Is there a way to delay the library integration by a specified time period, or even just 6 - 12 or 24 hrs?

**Closed as completed** 2024-06-20 14:16 UTC
Labels: bug
